var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/vogue/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__26ef992f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b9a0874._.js")
R.c("server/chunks/ssr/_a6424546._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d2bff17b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_77ec7569._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__6adae8ad._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_vogue_page_actions_e9ef9fd6.js")
R.m(66896)
module.exports=R.m(66896).exports
